---
title: "GroupAct3.rmd"
author: "Luis Carlo Sevilla"
date: "7/31/2021"
output: html_document
---
## I. Introduction

The goal of this study is to reduce the possibility of overcharge while at the same time providing a sufficient power supply. In a benchmark 0.4 kV network, optimization for a reduction in peak line loading reduces additional line loading percentages by over 10% or 5%. Said percentages are caused by incremental increases in the number of EVs charging an agent based Monte Carlo simulation. A Monte Carlo simulation serves the purpose of making mathematical estimations and mimicking operations of complex systems via random sampling and statistical modeling.$^{[1]}$ Optimization leads to an increase in voltage availability ranging from 1.5V to 7V. Optimization shows the savings in low voltage networks are negligible.

## II. Methodology

In this version of the study, the researchers chose to do random sampling in order to decrease the data measured. The number of cars and the number of hours were changed by the researchers in order for a more feasible study to be done. Two sample tests were made, one wherein there were only 10 cars while the other had 100 cars, both sample tests had the time of 12 hours. Two hypothesis were made for the study. The Null Hypothesis stated that $H_0: M_1-M_2 = 0$ or $M_1 = M_2$, while the Alternative Hypothesis stated that $H_1: M_1<M_2$. The consumption values were then calculated for using the test statistic formula $t_0 = \frac{\bar{x}_1 - \bar{x}_2 - \Delta_0} {S_p \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}$.

## III. Results

***Parameters: ***
$\alpha = 0.05$

$\bar{x}_1 = 0.1443870687$, $S_1 = 0.09425218829$, $n_1 = 10000$



$\bar{x}_2 = 0.1455762041$, $S_2 = 0.09490581053$, $n_2 = 10000$




**Case 1: ** $\sigma_1^2 =\sigma_2^2 = \sigma^2$



**Null Hypothesis: ** $H_0 : \mu_1-\mu_2 = 0$ or $\mu_1 = \mu_2$



**Alternative Hypothesis: ** $H_1 : \mu_1 < \mu_2$



**Test Statistics: ** $$t_0 = \frac{\bar{x}_1 - \bar{x}_2 - \Delta_0} {S_p \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}$$
**Reject $H_0$ if:** P-value $<0.05$ or $t_0 < -t_{\alpha,n_1+n_2-2}$



**Computations: **
$$S_p = \sqrt{\frac{(n_1-1)S_1^2 +(n_1-1)S_2^2}{n_1+n_2-2}}$$
$$S_p = \sqrt{\frac{(10000-1)(0.09425218829) +(10000-1)(0.09490581053)}{10000+10000-2}}$$
$$S_p = 0.09457956404$$
$$t_0 = \frac{0.1443870687 - 0.1455762041 - 0} {0.09457956404 \sqrt{\frac{1}{10000}+\frac{1}{10000}}}$$

$$t_0 = -0.8890352939$$
Looking at the **t-table** (since the degrees of freedom $= 19998$, we look at $\infty$)



P-value of $t_0 = (0.10<P(t_0)<0.25)< 0.05$ therefore, we **Fail to Reject** $H_0$



$$t_0 < -t_{0.05,\infty} : -0.889<-1.645 $$
***Failt to Reject*** $H_0$


## IV. Discussion

The test failed to reject the Null hypothesis, meaning that the energy consumption value of the 100 was not significantly greater than the consumption value of the 10 cars. The P-value was less than the alpha value which led the analysis to fail to reject the null hypothesis. Furthermore, the value of $t_0$ was less then the value of $-t_{0.05}$ which means the study failed to reject the null hypothesis based on the rejection region of the hypothesis test. The study intended to prove that the mean energy consumption value of the 100 cars ($\mu_1$) was greater than the mean consumption of the 10 cars ($\mu_2$) but failed to prove it due to the lack of significant evidence.

## V. Conclusion

There are no sufficient evidence to conclude that the number of electric vehicles charging affects the energy consumption of a certain household. This suggests a potential solution in optimizing the energy consumption of electric vehicles to decrease the potential of overloading a low voltage grid. This will be benificial for places where there are electric vehicle charging stations and for areas to be able to create their own charging station without having to invest in costly equipments. 

## References:

[1] R. L. Harrison, "Introduction To Monte Carlo Simulation," 5 January 2010. [Online]. Available: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2924739/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2924739/</a> . [Accessed 31 July 2021].
