% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Group Activity (Module 4)},
  pdfauthor={Karl Boncodin, Andrew Choa, Covi Perfecto, Luis Sevilla and Joshua Tirana},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Group Activity (Module 4)}
\author{Karl Boncodin, Andrew Choa, Covi Perfecto, Luis Sevilla and
Joshua Tirana}
\date{8/4/2021}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

\hypertarget{methodology}{%
\subsection{Methodology}\label{methodology}}

\hypertarget{results}{%
\subsection{Results}\label{results}}

For this situation, we want to test if () with a 95\% confidence
interval(\(\alpha\) = 0.05)

Null Hypothesis:

Alternative Hypothesis:

Test Statistic:

The data set provided are in large numbers so we use the console to test
the hypothesis.

Reject \(H_0\) if:

\begin{verbatim}
P-value < 0.05 or $|f_0|$ > $f_{\alpha,1,n-2}$
\end{verbatim}

Computations:

This is one using the code below:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TOTKWH }\OtherTok{\textless{}{-}}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{kwhTotal}
\NormalTok{TOTSES }\OtherTok{\textless{}{-}}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{totalSessions}
\NormalTok{simpleregress }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(TOTSES }\SpecialCharTok{\textasciitilde{}}\NormalTok{ TOTKWH, }\AttributeTok{data =}\NormalTok{ newdata)}
\FunctionTok{summary}\NormalTok{(simpleregress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = TOTSES ~ TOTKWH, data = newdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -98.781 -38.886  -4.627  28.705 110.994 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 100.7807     1.9346  52.095  < 2e-16 ***
## TOTKWH       -1.9940     0.2981  -6.689 2.61e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 50.24 on 3393 degrees of freedom
## Multiple R-squared:  0.01302,    Adjusted R-squared:  0.01273 
## F-statistic: 44.75 on 1 and 3393 DF,  p-value: 2.613e-11
\end{verbatim}

We find the coefficients for the regression model from the lm function
and our regression model would be: \[
  \hat{y} ~=~100.7807~-~1.9940x
\] Also in the lm function, we find out that

\(f_0\) = 44.75 and a p value = 2.613\(e^{-11}\)

And based on the criteria for rejection: \[
  f_0~=44.75~>~f_{0.05,1,3993}~=~3.84~~~and ~~~~P(f_0)=2.613e^{-11}~<~0.05
\] so we reject \(H_0\)

Then we test for true correlation where:

Null Hypothesis: \(H_0\): \(\rho\) = 0

Alternative Hypothesis: \(H_0\): \(\rho\) \(\ne\) 0

Test statistic: We will again use the console to compute for the t test
statistic.

Reject \(H_0\) if: \(|t_0|\) \textgreater{} \(t_{\alpha/2,n-2}\)

Computations:

We use the code below to get the test statistic for correlation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corellate }\OtherTok{\textless{}{-}} \FunctionTok{cor.test}\NormalTok{(TOTKWH, TOTSES, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{) }
\NormalTok{corellate}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  TOTKWH and TOTSES
## t = -6.6892, df = 3393, p-value = 2.613e-11
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.14716327 -0.08075797
## sample estimates:
##        cor 
## -0.1140881
\end{verbatim}

Based on result, our t value is -6.6892 and based on our criteria:

\[
|t_0| = 6.6892 > t_{0.025,3993} = 1.960
\]

Hence, we reject \(H_0\) and that the correlation coefficient is
\(\rho\) \(\ne\) 0. \#\# Discussion \#\# Conclusion

\end{document}
